### ISSUE TITLE
tip vs the rest

### ISSUE THREAD

**Issue by bep** [fortytw2/leaktest#7] opened 2016-04-29 18:50 UTC
See https://travis-ci.org/bep/debounce

I don't understand why a leak is reported on tip, but not on <= Go 1.6.

**Comment by fortytw2** [comment] 2016-05-02 11:47
Definitely smells funky. I'll set up travis on this repo later and see what happens on tip 👌

**Comment by fortytw2** [comment] 2016-05-03 15:01
Update here - can't reproduce on travis with the tests in this repo right now, I'll look through your code and try to come up with a test case :D

**Comment by belak** [comment] 2016-09-08 23:58
This might be able to be merged with #9

**Comment by fortytw2** [comment] 2016-09-23 13:37
closed by https://github.com/fortytw2/leaktest/pull/10

**Closed by fortytw2** 2016-09-23 13:37 UTC
